from setuptools import setup, find_packages

setup(
    name="adaptive-weather-attacks",
    version="0.1.0",
    author="Your Name",
    author_email="your.email@example.com",
    description="Adversarial weather attacks using Variable CFG diffusion",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/YOUR_USERNAME/adaptive-weather-attacks",
    packages=find_packages(),
    python_requires=">=3.8",
    install_requires=[
        "torch>=2.0.0",
        "torchvision>=0.15.0",
        "timm>=0.9.0",
        "transformers>=4.30.0",
        "diffusers>=0.21.0",
        "torchattacks>=3.4.0",
        "lpips>=0.1.4",
        "numpy>=1.24.0",
        "pandas>=2.0.0",
        "Pillow>=9.5.0",
        "matplotlib>=3.7.0",
        "tqdm>=4.65.0",
        "scikit-learn>=1.3.0",
        "PyYAML>=6.0",
    ],
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Science/Research",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
    ],
)
